"""update sneaker id

Revision ID: b1e27626636c
Revises: e82c344e3a5a
Create Date: 2018-12-23 04:41:10.540445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1e27626636c'
down_revision = 'e82c344e3a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sneaker_event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('sneaker_id', sa.String(length=120), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_sneaker_event_event_time'), 'sneaker_event', ['event_time'], unique=False)
    op.create_index(op.f('ix_sneaker_event_event_type'), 'sneaker_event', ['event_type'], unique=False)
    op.drop_index('ix_event_event_time', table_name='event')
    op.drop_index('ix_event_event_type', table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sneaker_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_id', name='event_pkey')
    )
    op.create_index('ix_event_event_type', 'event', ['event_type'], unique=False)
    op.create_index('ix_event_event_time', 'event', ['event_time'], unique=False)
    op.drop_index(op.f('ix_sneaker_event_event_type'), table_name='sneaker_event')
    op.drop_index(op.f('ix_sneaker_event_event_time'), table_name='sneaker_event')
    op.drop_table('sneaker_event')
    # ### end Alembic commands ###
